name: IIS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore C:\Users\naram\source\repos\ClaimsPrincipal\ClaimsPrincipal.sln

      - name: Build the project
        run: dotnet build C:\Users\naram\source\repos\ClaimsPrincipal\ClaimsPrincipal.sln --no-restore --configuration Release

      - name: Publish the project
        run: dotnet publish C:\Users\naram\source\repos\ClaimsPrincipal\ClaimsPrincipal.sln --configuration Release -o ${{ github.workspace }}/publish

      - name: Copy files to IIS folder
        run: |
          $iisFolder = 'C:\Users\naram\source\repos\Tap-CustomApps\ClaimsDeployment'
          Remove-Item -Recurse -Force $iisFolder\*
          Copy-Item -Path "${{ github.workspace }}\publish\*" -Destination $iisFolder -Recurse
        shell: pwsh
