name: Local IIS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: List entire directory structure for debugging
        run: |
          # Check directory structure from root of github.workspace
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore "${{ github.workspace }}\ClaimsPrincipal.csproj" # Adjust path if needed

      - name: Clean the project
        run: dotnet clean "${{ github.workspace }}\ClaimsPrincipal.csproj"

      - name: Build the project
        run: dotnet build "${{ github.workspace }}\ClaimsPrincipal.csproj" --no-restore --configuration Release

      - name: Publish the project
        run: dotnet publish "${{ github.workspace }}\ClaimsPrincipal.csproj" -c Release -o "${{ github.workspace }}\publish"

      - name: Copy files to IIS folder
        run: |
          # Define IIS folder path (set this to the folder IIS is serving, e.g., inetpub/wwwroot/YourAppFolderName)
          $iisFolder = 'C:\Users\naram\source\repos\Tap-CustomApps\ClaimsDeployment'

          # Remove existing files in IIS folder
          Remove-Item -Path "$iisFolder\*" -Recurse -Force

          # Copy new files to IIS folder
          Copy-Item -Path "${{ github.workspace }}\publish\*" -Destination "$iisFolder" -Recurse
        shell: pwsh
